server: 
  port: 8080
  context-path: /je

---  
    
spring: 
  profiles: local,default
datasource: 
    journalentries: 
      jdbcUrl: jdbc:h2:mem:je;Mode=Oracle
      username: SA
      password: 
      driverClassName: org.h2.Driver
      defaultSchema: 
      maxPoolSize: 3
      hibernate: 
        hbm2ddl.method: create-drop
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        
        